[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules', 'src']
gas_reports = ["HandshakeNft"
, "HandshakeTld"
, "HandshakeSld"
, "SldRegistrationManager"
, "TldClaimManager"
, "SldCommitIntent"
, "PaymentManager"
, "GlobalRegistrationRules"
, "DefaultRegistrationStrategy"
, "AddressResolver"
, "BaseResolver"
, "ContentHashResolver"
, "DefaultResolver"
, "DNSResolver"
, "NameResolver"
, "TextResolver"]
optimizer-runs = 10_000
via-ir=true

# Network profiles for deployment
[profile.optimism-mainnet]
rpc_url = "${OP_MAINNET_RPC_URL}"
private_key = "${PRIVATE_KEY}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"
chain_id = 10

[profile.optimism-sepolia]
rpc_url = "${OP_SEPOLIA_RPC_URL}"
private_key = "${TEST_PRIVATE_KEY}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"
chain_id = 11155420

# See more config options https://github.com/foundry-rs/foundry/tree/master/config